/**********************************************************************************
 * Copyright (c) 2026 borkdominik and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **********************************************************************************/
import { RandomStrategy } from './random.strategy.js';
import { type PropertyDescriptor, type ValueContext, type ValueStrategy } from './strategy.js';

/** Configuration for the {@link PatternStrategy}: a map of property name to format string. */
export interface PatternConfig {
    /**
     * Property name → format string. Supported placeholders:
     * - `{n}` — the 1-based index of the instance being generated.
     * - `{pick:a,b,c}` — a random pick from the comma-separated options.
     *
     * Any other text is emitted verbatim. Properties absent from this map are
     * generated by the fallback strategy.
     */
    patterns: Record<string, string>;
}

/** Matches `{n}` or `{pick:...}` placeholders; the capture holds the pick options. */
const PLACEHOLDER = /\{n\}|\{pick:([^}]*)\}/g;

function renderPattern(pattern: string, ctx: ValueContext): string {
    return pattern.replace(PLACEHOLDER, (match, pickOptions: string | undefined) => {
        if (match === '{n}') {
            return String(ctx.index);
        }
        const options = (pickOptions ?? '')
            .split(',')
            .map(option => option.trim())
            .filter(option => option.length > 0);
        return options.length > 0 ? ctx.rng.pick(options) : '';
    });
}

/**
 * Pattern/mock value strategy (topic feature 4c). Fills slots from user-provided
 * format strings — producing predictable, readable data such as
 * `name = "User_1"`, `email = "user1@example.com"`, `role = "guest"`.
 *
 * Properties without a configured pattern are delegated to the fallback strategy
 * (random by default), so a partial pattern configuration still yields a
 * complete instance.
 */
export class PatternStrategy implements ValueStrategy {
    readonly kind = 'pattern';

    private readonly fallback: ValueStrategy;

    constructor(
        private readonly config: PatternConfig,
        fallback: ValueStrategy = new RandomStrategy()
    ) {
        this.fallback = fallback;
    }

    value(property: PropertyDescriptor, ctx: ValueContext): string | undefined {
        const pattern = this.config.patterns[property.name];
        if (pattern === undefined) {
            return this.fallback.value(property, ctx);
        }
        return renderPattern(pattern, ctx);
    }
}
